#pragma checksum "C:\Users\Salim Mayaleh\source\repos\PersonalLibrary\PersonalLibrary.Client\Pages\Authors.cshtml" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "0808f32e02097fe1c96cb655b494c94d085c5068"
// <auto-generated/>
#pragma warning disable 1591
namespace PersonalLibrary.Client.Pages
{
    #line hidden
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Threading.Tasks;
    using Microsoft.AspNetCore.Blazor;
    using Microsoft.AspNetCore.Blazor.Components;
    using System.Net.Http;
    using Microsoft.AspNetCore.Blazor.Layouts;
    using Microsoft.AspNetCore.Blazor.Routing;
    using Microsoft.JSInterop;
    using PersonalLibrary.Client;
    using PersonalLibrary.Client.Shared;
    using PersonalLibrary.Shared;
    [Microsoft.AspNetCore.Blazor.Layouts.LayoutAttribute(typeof(MainLayout))]

    [Microsoft.AspNetCore.Blazor.Components.RouteAttribute("/all-authors")]
    public class Authors : Microsoft.AspNetCore.Blazor.Components.BlazorComponent
    {
        #pragma warning disable 1998
        protected override void BuildRenderTree(Microsoft.AspNetCore.Blazor.RenderTree.RenderTreeBuilder builder)
        {
            base.BuildRenderTree(builder);
            builder.OpenComponent<PersonalLibrary.Client.Shared.SurveyPrompt>(0);
            builder.AddAttribute(1, "Title", "All Authors");
            builder.CloseComponent();
            builder.AddContent(2, "\n\n");
            builder.AddMarkupContent(3, "<h1>All Authors</h1>\n\n");
            builder.OpenElement(4, "p");
            builder.AddContent(5, "\n    ");
            builder.OpenComponent<Microsoft.AspNetCore.Blazor.Routing.NavLink>(6);
            builder.AddAttribute(7, "href", "form-author");
            builder.AddAttribute(8, "Match", Microsoft.AspNetCore.Blazor.Components.RuntimeHelpers.TypeCheck<Microsoft.AspNetCore.Blazor.Routing.NavLinkMatch>(NavLinkMatch.All));
            builder.AddAttribute(9, "ChildContent", (Microsoft.AspNetCore.Blazor.RenderFragment)((builder2) => {
                builder2.AddContent(10, "\n        ");
                builder2.AddMarkupContent(11, "<button class=\"btn btn-primary\">\n            <span class=\"oi oi-plus\"></span>\n            Add Author\n        </button>\n    ");
            }
            ));
            builder.CloseComponent();
            builder.AddContent(12, "\n");
            builder.CloseElement();
            builder.AddContent(13, "\n\n");
#line 19 "C:\Users\Salim Mayaleh\source\repos\PersonalLibrary\PersonalLibrary.Client\Pages\Authors.cshtml"
 if (authors == null)
{

#line default
#line hidden
            builder.AddContent(14, "    ");
            builder.AddMarkupContent(15, "<div class=\"text-center\">\n        <div class=\"spinner-border\" role=\"status\">\n            <span class=\"sr-only\">Loading...</span>\n        </div>\n    </div>\n");
#line 26 "C:\Users\Salim Mayaleh\source\repos\PersonalLibrary\PersonalLibrary.Client\Pages\Authors.cshtml"
}
else
{

#line default
#line hidden
            builder.AddContent(16, "    ");
            builder.AddMarkupContent(17, "<div class=\"row\">\n\n    </div>\n    ");
            builder.OpenElement(18, "table");
            builder.AddAttribute(19, "class", "table");
            builder.AddContent(20, "\n        ");
            builder.AddMarkupContent(21, "<thead>\n            <tr>\n                <th>Author Name</th>\n                <th>About Author</th>\n                <th>Action</th>\n            </tr>\n        </thead>\n        ");
            builder.OpenElement(22, "tbody");
            builder.AddContent(23, "\n");
#line 41 "C:\Users\Salim Mayaleh\source\repos\PersonalLibrary\PersonalLibrary.Client\Pages\Authors.cshtml"
             foreach (var author in authors)
            {

#line default
#line hidden
            builder.AddContent(24, "                ");
            builder.OpenElement(25, "tr");
            builder.AddContent(26, "\n                    ");
            builder.OpenElement(27, "td");
            builder.OpenElement(28, "a");
            builder.AddAttribute(29, "href", "#");
            builder.AddContent(30, author.Name);
            builder.CloseElement();
            builder.CloseElement();
            builder.AddContent(31, "\n                    ");
            builder.OpenElement(32, "td");
            builder.OpenElement(33, "a");
            builder.AddAttribute(34, "href", "#");
            builder.AddContent(35, author.About);
            builder.CloseElement();
            builder.CloseElement();
            builder.AddContent(36, "\n                    ");
            builder.OpenElement(37, "td");
            builder.OpenElement(38, "a");
            builder.AddAttribute(39, "class", "btn btn-success");
            builder.AddAttribute(40, "href", "/edit-author/" + (author.Authorid));
            builder.AddContent(41, "Edit");
            builder.CloseElement();
            builder.AddContent(42, " | ");
            builder.OpenElement(43, "a");
            builder.AddAttribute(44, "class", "btn btn-danger");
            builder.AddAttribute(45, "href", "/delete-author/" + (author.Authorid));
            builder.AddContent(46, "Delete");
            builder.CloseElement();
            builder.CloseElement();
            builder.AddContent(47, "\n                ");
            builder.CloseElement();
            builder.AddContent(48, "\n");
#line 48 "C:\Users\Salim Mayaleh\source\repos\PersonalLibrary\PersonalLibrary.Client\Pages\Authors.cshtml"
            }

#line default
#line hidden
            builder.AddContent(49, "        ");
            builder.CloseElement();
            builder.AddContent(50, "\n    ");
            builder.CloseElement();
            builder.AddContent(51, "\n");
#line 51 "C:\Users\Salim Mayaleh\source\repos\PersonalLibrary\PersonalLibrary.Client\Pages\Authors.cshtml"
}

#line default
#line hidden
        }
        #pragma warning restore 1998
#line 53 "C:\Users\Salim Mayaleh\source\repos\PersonalLibrary\PersonalLibrary.Client\Pages\Authors.cshtml"
            
/* ukazka, jak nastavit componente parametr: */
/*
[Parameter]
private string Title { get; set; }
*/

Author[] authors;
/*
 * Volani api server
 */
protected override async Task OnInitAsync()
{

    //books = await Http.GetJsonAsync<Book[]>("sample-data/books.json");

    authors = await Http.GetJsonAsync<Author[]>("api/mylibrary/getAuthors");
}

#line default
#line hidden
        [global::Microsoft.AspNetCore.Blazor.Components.InjectAttribute] private HttpClient Http { get; set; }
    }
}
#pragma warning restore 1591
