#pragma checksum "C:\Users\Salim Mayaleh\source\repos\PersonalLibrary\PersonalLibrary.Client\Pages\FormAuthor.cshtml" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "8777f5566501ec031d57fe7142517b3c4ba43c0b"
// <auto-generated/>
#pragma warning disable 1591
#pragma warning disable 0414
#pragma warning disable 0649
#pragma warning disable 0169

namespace PersonalLibrary.Client.Pages
{
    #line hidden
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Threading.Tasks;
    using Microsoft.AspNetCore.Blazor;
    using Microsoft.AspNetCore.Blazor.Components;
    using System.Net.Http;
    using Microsoft.AspNetCore.Blazor.Layouts;
    using Microsoft.AspNetCore.Blazor.Routing;
    using Microsoft.JSInterop;
    using PersonalLibrary.Client;
    using PersonalLibrary.Client.Shared;
    using PersonalLibrary.Shared;
    [Microsoft.AspNetCore.Blazor.Layouts.LayoutAttribute(typeof(MainLayout))]

    [Microsoft.AspNetCore.Blazor.Components.RouteAttribute("/form-author")]
    public class FormAuthor : Microsoft.AspNetCore.Blazor.Components.BlazorComponent
    {
        #pragma warning disable 1998
        protected override void BuildRenderTree(Microsoft.AspNetCore.Blazor.RenderTree.RenderTreeBuilder builder)
        {
        }
        #pragma warning restore 1998
#line 67 "C:\Users\Salim Mayaleh\source\repos\PersonalLibrary\PersonalLibrary.Client\Pages\FormAuthor.cshtml"
            
    private string _newName = "";

    Author formAuthor = new Author();
    bool CanClickSave = true;
    bool IsInvalidName = false;
    //protected override void OnInit()
    protected void AddAuthor()
    {
        if(string.IsNullOrEmpty(formAuthor.Name))
        {
            IsInvalidName = true;
            return;
        }
        IsInvalidName = false;
        CanClickSave = false;
        Http.SendJsonAsync(HttpMethod.Post, "/api/mylibrary/addAuthor", formAuthor);
        _newName = formAuthor.Name;
        formAuthor.Name = null;
        formAuthor.About = null;
        CanClickSave = true;

        //UriHelper.NavigateTo("/form-author");
    }

#line default
#line hidden
        [global::Microsoft.AspNetCore.Blazor.Components.InjectAttribute] private Microsoft.AspNetCore.Blazor.Services.IUriHelper UriHelper { get; set; }
        [global::Microsoft.AspNetCore.Blazor.Components.InjectAttribute] private HttpClient Http { get; set; }
    }
}
#pragma warning restore 1591
