#pragma checksum "C:\Users\Salim Mayaleh\source\repos\PersonalLibrary\PersonalLibrary.Client\Pages\FormAuthor.cshtml" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "8777f5566501ec031d57fe7142517b3c4ba43c0b"
// <auto-generated/>
#pragma warning disable 1591
namespace PersonalLibrary.Client.Pages
{
    #line hidden
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Threading.Tasks;
    using Microsoft.AspNetCore.Blazor;
    using Microsoft.AspNetCore.Blazor.Components;
    using System.Net.Http;
    using Microsoft.AspNetCore.Blazor.Layouts;
    using Microsoft.AspNetCore.Blazor.Routing;
    using Microsoft.JSInterop;
    using PersonalLibrary.Client;
    using PersonalLibrary.Client.Shared;
    using PersonalLibrary.Shared;
    [Microsoft.AspNetCore.Blazor.Layouts.LayoutAttribute(typeof(MainLayout))]

    [Microsoft.AspNetCore.Blazor.Components.RouteAttribute("/form-author")]
    public class FormAuthor : Microsoft.AspNetCore.Blazor.Components.BlazorComponent
    {
        #pragma warning disable 1998
        protected override void BuildRenderTree(Microsoft.AspNetCore.Blazor.RenderTree.RenderTreeBuilder builder)
        {
            base.BuildRenderTree(builder);
            builder.OpenComponent<PersonalLibrary.Client.Shared.SurveyPrompt>(0);
            builder.AddAttribute(1, "Title", "New Author");
            builder.CloseComponent();
            builder.AddContent(2, "\n\n");
            builder.OpenElement(3, "div");
            builder.AddAttribute(4, "class", "row");
            builder.AddContent(5, "\n\n    ");
            builder.AddMarkupContent(6, "<div class=\"col-4\">\n        <h2>Adding new Author or Book Writter:</h2>\n        <p>Please fill at least Author Name.</p>\n    </div>\n\n    ");
            builder.OpenElement(7, "div");
            builder.AddAttribute(8, "class", "col-4");
            builder.AddContent(9, "\n        ");
            builder.OpenElement(10, "div");
            builder.AddAttribute(11, "class", "form-group");
            builder.AddContent(12, "\n            ");
            builder.AddMarkupContent(13, "<label for=\"nameAuthor\">Author Name:</label>\n            ");
            builder.OpenElement(14, "input");
            builder.AddAttribute(15, "type", "text");
            builder.AddAttribute(16, "class", "form-control is-valid");
            builder.AddAttribute(17, "id", "nameAuthor");
            builder.AddAttribute(18, "aria-describedby", "nameHelp");
            builder.AddAttribute(19, "placeholder", "name");
            builder.AddAttribute(20, "required", true);
            builder.AddAttribute(21, "value", Microsoft.AspNetCore.Blazor.Components.BindMethods.GetValue(formAuthor.Name));
            builder.AddAttribute(22, "onchange", Microsoft.AspNetCore.Blazor.Components.BindMethods.SetValueHandler(__value => formAuthor.Name = __value, formAuthor.Name));
            builder.CloseElement();
            builder.AddContent(23, "\n            ");
            builder.AddMarkupContent(24, "<small id=\"nameHelp\" class=\"form-text text-muted\">Everyone has at least name.</small>\n            \n            ");
            builder.AddMarkupContent(25, "<div class=\"invalid-feedback\">\n                Please fill name.\n            </div>\n");
#line 29 "C:\Users\Salim Mayaleh\source\repos\PersonalLibrary\PersonalLibrary.Client\Pages\FormAuthor.cshtml"
             if (IsInvalidName)
            {

#line default
#line hidden
            builder.AddContent(26, "                ");
            builder.AddMarkupContent(27, "<span class=\"small form-text text-danger\">Please fill this!</span>\n");
#line 32 "C:\Users\Salim Mayaleh\source\repos\PersonalLibrary\PersonalLibrary.Client\Pages\FormAuthor.cshtml"
            }

#line default
#line hidden
            builder.AddContent(28, "        ");
            builder.CloseElement();
            builder.AddContent(29, "\n    ");
            builder.CloseElement();
            builder.AddContent(30, "\n\n    ");
            builder.OpenElement(31, "div");
            builder.AddAttribute(32, "class", "col-4");
            builder.AddContent(33, "\n\n        ");
            builder.OpenElement(34, "div");
            builder.AddAttribute(35, "class", "form-group");
            builder.AddContent(36, "\n            ");
            builder.AddMarkupContent(37, "<label for=\"aboutAuthor\">About Author</label>\n            ");
            builder.OpenElement(38, "textarea");
            builder.AddAttribute(39, "class", "form-control");
            builder.AddAttribute(40, "id", "aboutAuthor");
            builder.AddAttribute(41, "aria-describedby", "aboutHelp");
            builder.AddAttribute(42, "placeholder", "about");
            builder.AddAttribute(43, "rows", "3");
            builder.AddAttribute(44, "value", Microsoft.AspNetCore.Blazor.Components.BindMethods.GetValue(formAuthor.About));
            builder.AddAttribute(45, "onchange", Microsoft.AspNetCore.Blazor.Components.BindMethods.SetValueHandler(__value => formAuthor.About = __value, formAuthor.About));
            builder.CloseElement();
            builder.AddContent(46, "\n            ");
            builder.AddMarkupContent(47, "<small id=\"aboutHelp\" class=\"form-text text-muted\">For example copy some text about the author from wiki and paste it there</small>\n        ");
            builder.CloseElement();
            builder.AddContent(48, "\n    ");
            builder.CloseElement();
            builder.AddContent(49, "\n");
            builder.CloseElement();
            builder.AddContent(50, "\n");
#line 45 "C:\Users\Salim Mayaleh\source\repos\PersonalLibrary\PersonalLibrary.Client\Pages\FormAuthor.cshtml"
 if (CanClickSave)
{


#line default
#line hidden
            builder.AddContent(51, "    ");
            builder.OpenElement(52, "button");
            builder.AddAttribute(53, "onclick", Microsoft.AspNetCore.Blazor.Components.BindMethods.GetEventHandlerValue<Microsoft.AspNetCore.Blazor.UIMouseEventArgs>(AddAuthor));
            builder.AddAttribute(54, "class", "btn btn-primary");
            builder.AddContent(55, "Add Author");
            builder.CloseElement();
            builder.AddContent(56, "\n");
#line 49 "C:\Users\Salim Mayaleh\source\repos\PersonalLibrary\PersonalLibrary.Client\Pages\FormAuthor.cshtml"
}
else
{

#line default
#line hidden
            builder.AddContent(57, "    ");
            builder.AddMarkupContent(58, "<div class=\"text-center\">\n        <div class=\"spinner-border\" role=\"status\">\n            <span class=\"sr-only\">Processing...</span>\n        </div>\n    </div>\n");
#line 57 "C:\Users\Salim Mayaleh\source\repos\PersonalLibrary\PersonalLibrary.Client\Pages\FormAuthor.cshtml"
}

#line default
#line hidden
            builder.AddContent(59, "\n");
#line 59 "C:\Users\Salim Mayaleh\source\repos\PersonalLibrary\PersonalLibrary.Client\Pages\FormAuthor.cshtml"
 if (_newName != "")
{

#line default
#line hidden
            builder.AddContent(60, "    ");
            builder.OpenElement(61, "div");
            builder.AddAttribute(62, "class", "alert alert-success");
            builder.AddAttribute(63, "role", "alert");
            builder.AddContent(64, "\n        New Author added: ");
            builder.OpenElement(65, "b");
            builder.AddContent(66, _newName);
            builder.CloseElement();
            builder.AddContent(67, "\n    ");
            builder.CloseElement();
            builder.AddContent(68, "\n");
#line 64 "C:\Users\Salim Mayaleh\source\repos\PersonalLibrary\PersonalLibrary.Client\Pages\FormAuthor.cshtml"

}

#line default
#line hidden
        }
        #pragma warning restore 1998
#line 67 "C:\Users\Salim Mayaleh\source\repos\PersonalLibrary\PersonalLibrary.Client\Pages\FormAuthor.cshtml"
            
    private string _newName = "";

    Author formAuthor = new Author();
    bool CanClickSave = true;
    bool IsInvalidName = false;
    //protected override void OnInit()
    protected void AddAuthor()
    {
        if(string.IsNullOrEmpty(formAuthor.Name))
        {
            IsInvalidName = true;
            return;
        }
        IsInvalidName = false;
        CanClickSave = false;
        Http.SendJsonAsync(HttpMethod.Post, "/api/mylibrary/addAuthor", formAuthor);
        _newName = formAuthor.Name;
        formAuthor.Name = null;
        formAuthor.About = null;
        CanClickSave = true;

        //UriHelper.NavigateTo("/form-author");
    }

#line default
#line hidden
        [global::Microsoft.AspNetCore.Blazor.Components.InjectAttribute] private Microsoft.AspNetCore.Blazor.Services.IUriHelper UriHelper { get; set; }
        [global::Microsoft.AspNetCore.Blazor.Components.InjectAttribute] private HttpClient Http { get; set; }
    }
}
#pragma warning restore 1591
