#pragma checksum "C:\Users\Salim Mayaleh\source\repos\PersonalLibrary\PersonalLibrary.Client\Pages\FormBook.cshtml" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "eac8aeb22526c4b5375a6c0dfcd41963bfd22d94"
// <auto-generated/>
#pragma warning disable 1591
namespace PersonalLibrary.Client.Pages
{
    #line hidden
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Threading.Tasks;
    using Microsoft.AspNetCore.Blazor;
    using Microsoft.AspNetCore.Blazor.Components;
    using System.Net.Http;
    using Microsoft.AspNetCore.Blazor.Layouts;
    using Microsoft.AspNetCore.Blazor.Routing;
    using Microsoft.JSInterop;
    using PersonalLibrary.Client;
    using PersonalLibrary.Client.Shared;
    using PersonalLibrary.Shared;
    [Microsoft.AspNetCore.Blazor.Layouts.LayoutAttribute(typeof(MainLayout))]

    [Microsoft.AspNetCore.Blazor.Components.RouteAttribute("/form-book")]
    public class FormBook : Microsoft.AspNetCore.Blazor.Components.BlazorComponent
    {
        #pragma warning disable 1998
        protected override void BuildRenderTree(Microsoft.AspNetCore.Blazor.RenderTree.RenderTreeBuilder builder)
        {
            base.BuildRenderTree(builder);
#line 7 "C:\Users\Salim Mayaleh\source\repos\PersonalLibrary\PersonalLibrary.Client\Pages\FormBook.cshtml"
 if (IsEdit && formBook.Bookid == 0)
{

#line default
#line hidden
            builder.AddContent(0, "    ");
            builder.AddMarkupContent(1, "<div class=\"text-center\">\n        <div class=\"spinner-border\" role=\"status\">\n            <span class=\"sr-only\">Loading...</span>\n        </div>\n    </div>\n");
#line 14 "C:\Users\Salim Mayaleh\source\repos\PersonalLibrary\PersonalLibrary.Client\Pages\FormBook.cshtml"
}
else
{

#line default
#line hidden
            builder.AddContent(2, "    ");
            builder.OpenElement(3, "div");
            builder.AddAttribute(4, "class", "row");
            builder.AddContent(5, "\n\n        ");
            builder.OpenElement(6, "div");
            builder.AddAttribute(7, "class", "col-4");
            builder.AddContent(8, "\n            ");
            builder.OpenElement(9, "h2");
            builder.AddContent(10, nadpis);
            builder.AddContent(11, ":");
            builder.CloseElement();
            builder.AddContent(12, "\n            ");
            builder.AddMarkupContent(13, "<p>Please fill at least Book Name.</p>\n        ");
            builder.CloseElement();
            builder.AddContent(14, "\n\n        ");
            builder.OpenElement(15, "div");
            builder.AddAttribute(16, "class", "col");
            builder.AddContent(17, "\n            ");
            builder.OpenElement(18, "div");
            builder.AddAttribute(19, "class", "form-group");
            builder.AddContent(20, "\n                ");
            builder.AddMarkupContent(21, "<label for=\"nameBook\">Book Name:</label>\n                ");
            builder.OpenElement(22, "input");
            builder.AddAttribute(23, "type", "text");
            builder.AddAttribute(24, "class", "form-control is-valid");
            builder.AddAttribute(25, "id", "nameBook");
            builder.AddAttribute(26, "aria-describedby", "bnameHelp");
            builder.AddAttribute(27, "placeholder", "book name");
            builder.AddAttribute(28, "required", true);
            builder.AddAttribute(29, "value", Microsoft.AspNetCore.Blazor.Components.BindMethods.GetValue(formBook.Name));
            builder.AddAttribute(30, "onchange", Microsoft.AspNetCore.Blazor.Components.BindMethods.SetValueHandler(__value => formBook.Name = __value, formBook.Name));
            builder.CloseElement();
            builder.AddContent(31, "\n                ");
            builder.AddMarkupContent(32, "<small id=\"bnameHelp\" class=\"form-text text-muted\">All Books has at least name.</small>\n                \n                ");
            builder.AddMarkupContent(33, "<div class=\"invalid-feedback\">\n                    Please fill name.\n                </div>\n");
#line 37 "C:\Users\Salim Mayaleh\source\repos\PersonalLibrary\PersonalLibrary.Client\Pages\FormBook.cshtml"
                 if (IsInvalidName)
                {

#line default
#line hidden
            builder.AddContent(34, "                    ");
            builder.AddMarkupContent(35, "<span class=\"small form-text text-danger\">Please fill this!</span>\n");
#line 40 "C:\Users\Salim Mayaleh\source\repos\PersonalLibrary\PersonalLibrary.Client\Pages\FormBook.cshtml"
                }

#line default
#line hidden
            builder.AddContent(36, "            ");
            builder.CloseElement();
            builder.AddContent(37, "\n        ");
            builder.CloseElement();
            builder.AddContent(38, "\n\n        ");
            builder.OpenElement(39, "div");
            builder.AddAttribute(40, "class", "col");
            builder.AddContent(41, "\n            ");
            builder.OpenElement(42, "div");
            builder.AddAttribute(43, "class", "form-group");
            builder.AddContent(44, "\n                ");
            builder.AddMarkupContent(45, "<label for=\"nameAuthor\">Author Name:</label>\n                ");
            builder.OpenElement(46, "input");
            builder.AddAttribute(47, "type", "text");
            builder.AddAttribute(48, "class", "form-control");
            builder.AddAttribute(49, "id", "nameAuthor");
            builder.AddAttribute(50, "aria-describedby", "anameHelp");
            builder.AddAttribute(51, "placeholder", "author name");
            builder.AddAttribute(52, "value", Microsoft.AspNetCore.Blazor.Components.BindMethods.GetValue(formBook.Author.Name));
            builder.AddAttribute(53, "onchange", Microsoft.AspNetCore.Blazor.Components.BindMethods.SetValueHandler(__value => formBook.Author.Name = __value, formBook.Author.Name));
            builder.CloseElement();
            builder.AddContent(54, "\n            ");
            builder.CloseElement();
            builder.AddContent(55, "\n        ");
            builder.CloseElement();
            builder.AddContent(56, "\n\n        ");
            builder.OpenElement(57, "div");
            builder.AddAttribute(58, "class", "col");
            builder.AddContent(59, "\n            ");
            builder.OpenElement(60, "div");
            builder.AddAttribute(61, "class", "form-group");
            builder.AddContent(62, "\n                ");
            builder.AddMarkupContent(63, "<label for=\"place\">Place:</label>\n                ");
            builder.OpenElement(64, "input");
            builder.AddAttribute(65, "type", "text");
            builder.AddAttribute(66, "class", "form-control");
            builder.AddAttribute(67, "id", "place");
            builder.AddAttribute(68, "placeholder", "place");
            builder.AddAttribute(69, "value", Microsoft.AspNetCore.Blazor.Components.BindMethods.GetValue(formBook.Place));
            builder.AddAttribute(70, "onchange", Microsoft.AspNetCore.Blazor.Components.BindMethods.SetValueHandler(__value => formBook.Place = __value, formBook.Place));
            builder.CloseElement();
            builder.AddContent(71, "\n            ");
            builder.CloseElement();
            builder.AddContent(72, "\n        ");
            builder.CloseElement();
            builder.AddContent(73, "\n\n        ");
            builder.OpenElement(74, "div");
            builder.AddAttribute(75, "class", "col");
            builder.AddContent(76, "\n\n            ");
            builder.OpenElement(77, "div");
            builder.AddAttribute(78, "class", "form-group");
            builder.AddContent(79, "\n                ");
            builder.AddMarkupContent(80, "<label for=\"aboutBook\">About Book</label>\n                ");
            builder.OpenElement(81, "textarea");
            builder.AddAttribute(82, "class", "form-control");
            builder.AddAttribute(83, "id", "aboutBook");
            builder.AddAttribute(84, "aria-describedby", "aboutHelp");
            builder.AddAttribute(85, "placeholder", "about");
            builder.AddAttribute(86, "rows", "3");
            builder.AddAttribute(87, "value", Microsoft.AspNetCore.Blazor.Components.BindMethods.GetValue(formBook.About));
            builder.AddAttribute(88, "onchange", Microsoft.AspNetCore.Blazor.Components.BindMethods.SetValueHandler(__value => formBook.About = __value, formBook.About));
            builder.CloseElement();
            builder.AddContent(89, "\n                ");
            builder.AddMarkupContent(90, "<small id=\"aboutHelp\" class=\"form-text text-muted\">For example copy some text about the book from wiki and paste it there</small>\n            ");
            builder.CloseElement();
            builder.AddContent(91, "\n        ");
            builder.CloseElement();
            builder.AddContent(92, "\n\n    ");
            builder.CloseElement();
            builder.AddContent(93, "\n");
#line 68 "C:\Users\Salim Mayaleh\source\repos\PersonalLibrary\PersonalLibrary.Client\Pages\FormBook.cshtml"
     if (CanClickSave)
    {
        

#line default
#line hidden
#line 70 "C:\Users\Salim Mayaleh\source\repos\PersonalLibrary\PersonalLibrary.Client\Pages\FormBook.cshtml"
         if (IsEdit)
        {

#line default
#line hidden
            builder.AddContent(94, "            ");
            builder.OpenElement(95, "button");
            builder.AddAttribute(96, "onclick", Microsoft.AspNetCore.Blazor.Components.BindMethods.GetEventHandlerValue<Microsoft.AspNetCore.Blazor.UIMouseEventArgs>(EditBook));
            builder.AddAttribute(97, "class", "btn btn-primary");
            builder.AddContent(98, "Edit Book");
            builder.CloseElement();
            builder.AddContent(99, "\n");
#line 73 "C:\Users\Salim Mayaleh\source\repos\PersonalLibrary\PersonalLibrary.Client\Pages\FormBook.cshtml"
        }
        else
        {

#line default
#line hidden
            builder.AddContent(100, "            ");
            builder.OpenElement(101, "button");
            builder.AddAttribute(102, "onclick", Microsoft.AspNetCore.Blazor.Components.BindMethods.GetEventHandlerValue<Microsoft.AspNetCore.Blazor.UIMouseEventArgs>(AddBook));
            builder.AddAttribute(103, "class", "btn btn-primary");
            builder.AddContent(104, "Add Book");
            builder.CloseElement();
            builder.AddContent(105, "\n");
#line 77 "C:\Users\Salim Mayaleh\source\repos\PersonalLibrary\PersonalLibrary.Client\Pages\FormBook.cshtml"
        }

#line default
#line hidden
#line 77 "C:\Users\Salim Mayaleh\source\repos\PersonalLibrary\PersonalLibrary.Client\Pages\FormBook.cshtml"
         
    }
    else
    {

#line default
#line hidden
            builder.AddContent(106, "        ");
            builder.AddMarkupContent(107, "<div class=\"text-center\">\n            <div class=\"spinner-border\" role=\"status\">\n                <span class=\"sr-only\">Processing...</span>\n            </div>\n        </div>\n");
#line 86 "C:\Users\Salim Mayaleh\source\repos\PersonalLibrary\PersonalLibrary.Client\Pages\FormBook.cshtml"
    }

#line default
#line hidden
#line 88 "C:\Users\Salim Mayaleh\source\repos\PersonalLibrary\PersonalLibrary.Client\Pages\FormBook.cshtml"
     if (_newName != "")
    {

#line default
#line hidden
            builder.AddContent(108, "        ");
            builder.OpenElement(109, "div");
            builder.AddAttribute(110, "class", "alert alert-success");
            builder.AddAttribute(111, "role", "alert");
            builder.AddContent(112, "\n            Book saved: ");
            builder.OpenElement(113, "b");
            builder.AddContent(114, _newName);
            builder.CloseElement();
            builder.AddContent(115, "\n        ");
            builder.CloseElement();
            builder.AddContent(116, "\n");
#line 93 "C:\Users\Salim Mayaleh\source\repos\PersonalLibrary\PersonalLibrary.Client\Pages\FormBook.cshtml"

    }

#line default
#line hidden
#line 94 "C:\Users\Salim Mayaleh\source\repos\PersonalLibrary\PersonalLibrary.Client\Pages\FormBook.cshtml"
     
}

#line default
#line hidden
        }
        #pragma warning restore 1998
#line 104 "C:\Users\Salim Mayaleh\source\repos\PersonalLibrary\PersonalLibrary.Client\Pages\FormBook.cshtml"
            
    private string _newName = "";

    Book formBook = new Book()
    {
        Author = new Author()
    };

    bool CanClickSave = true;
    bool IsInvalidName = false;
    //protected override void OnInit() //synch call

    bool isLoaded = false;

    [Parameter]
    bool IsEdit { get; set; } = false;

    [Parameter]
    int BookId { get; set; }

    string nadpis = "";

    protected override async Task OnInitAsync()
    {
        if (IsEdit)
        {
            nadpis = "Editing book";
            formBook = await Http.GetJsonAsync<Book>("/api/mylibrary/bookDetail/" + Convert.ToInt32(BookId));
            isLoaded = true;
        }
        else
        {
            nadpis = "Adding new book";
        }

    }
    
    protected void AddBook()
    {
        if (IsEdit)
        {
            return;
        }
        if (string.IsNullOrEmpty(formBook.Name))
        {
            IsInvalidName = true;
            return;
        }
        IsInvalidName = false;
        CanClickSave = false;
        Http.SendJsonAsync(HttpMethod.Post, "/api/mylibrary/addBook", formBook);
        _newName = formBook.Name;
        formBook.Name = null;
        formBook.About = null;
        formBook.Place = null;
        formBook.Author.Name = null;
        CanClickSave = true;

        //UriHelper.NavigateTo("/form-author");
    }

    protected void EditBook()
    {
        if (string.IsNullOrEmpty(formBook.Name))
        {
            IsInvalidName = true;
            return;
        }
        IsInvalidName = false;
        CanClickSave = false;
        Http.SendJsonAsync(HttpMethod.Post, "/api/mylibrary/editBook", formBook);
        _newName = formBook.Name;
        formBook = null;
        CanClickSave = true;
    }

#line default
#line hidden
        [global::Microsoft.AspNetCore.Blazor.Components.InjectAttribute] private Microsoft.AspNetCore.Blazor.Services.IUriHelper UriHelper { get; set; }
        [global::Microsoft.AspNetCore.Blazor.Components.InjectAttribute] private HttpClient Http { get; set; }
    }
}
#pragma warning restore 1591
